apiVersion: apps/v1
kind: Deployment
metadata:
  name: ft-lgtm-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ft-lgtm-backend
  template:
    metadata:
      labels:
        app: ft-lgtm-backend
    spec:
      containers:
        - name: ft-lgtm-backend
          image: ft-lgtm-backend:local
          imagePullPolicy: Never
          env:
            - name: HOST
              value: "0.0.0.0"
