apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ft-lgtm-ingress
spec:
  rules:
  - host: lgtm.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: ft-lgtm-backend
            port:
              number: 11000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ft-lgtm-frontend
            port:
              number: 11001
  - host: ipfs.lgtm.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ft-lgtm-ipfs-node
            port:
              name: gateway
  - host: grafana.lgtm.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ft-lgtm-observability
            port:
              name: grafana
