apiVersion: v1
kind: Service
metadata:
  name: ft-lgtm-observability
spec:
  selector:
    app: ft-lgtm-observability
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
