apiVersion: apps/v1
kind: Deployment
metadata:
  name: ft-lgtm-ipfs-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ft-lgtm-ipfs-node
  template:
    metadata:
      labels:
        app: ft-lgtm-ipfs-node
    spec:
      containers:
        - name: ft-lgtm-ipfs-node
          image: ipfs/kubo:v0.42.0
          imagePullPolicy: IfNotPresent
