apiVersion: v1
kind: Service
metadata:
  name: ft-lgtm-ipfs-node
spec:
  selector:
    app: ft-lgtm-ipfs-node
  ports:
    - name: api
      port: 5001
      targetPort: 5001
    - name: gateway
      port: 8080
      targetPort: 8080
